<?php

/**
 * AUTOGENERATED FILE, DO NOT EDIT
 *
 * By default the version number starts from 00000000-0
 *
 * After running command "npm run ver", the version number will become the
 * current date, followed by incremented number (on each run, the value after '-'
 * will increment by one).
 *
 * Do not edit the line which defines "DX_ASSETS_VERSION" as it's being targeted
 * with a REGEX expression from root/index.js file.
 */
if ( ! defined( 'DX_ASSETS_VERSION' ) ) {
	define( 'DX_ASSETS_VERSION', '20190525-11' );
}
